# Generated by Django 3.1.5 on 2023-12-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('telefone', models.CharField(max_length=14, unique=True)),
                ('cep', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('identificacao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('placa', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('modelo', models.CharField(max_length=20)),
                ('ano_veiculo', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mecanica.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('numero_ordem', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('servico', models.ManyToManyField(to='mecanica.Servico')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mecanica.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoManutencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_de_servico', models.ManyToManyField(to='mecanica.OrdemDeServico')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mecanica.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='AgendamentoServico',
            fields=[
                ('numero_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_agendamento', models.DateField()),
                ('data_previsao', models.DateField()),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mecanica.veiculo')),
            ],
        ),
    ]
