# Generated by Django 3.1.5 on 2023-12-08 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='mecanico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='mecanica.mecanico'),
        ),
    ]
