# Generated by Django 3.1.5 on 2023-12-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0004_auto_20231211_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamentoservico',
            old_name='data_agendamento',
            new_name='data_previsao_entrada',
        ),
        migrations.RenameField(
            model_name='agendamentoservico',
            old_name='data_previsao',
            new_name='data_previsao_saida',
        ),
    ]
